from __future__ import annotations

import libcst.matchers as m

MODEL_FIELD_TYPE = m.OneOf(
    m.Name("AutoField"),
    m.Name("BigAutoField"),
    m.Name("BigIntegerField"),
    m.Name("BinaryField"),
    m.Name("BooleanField"),
    m.Name("CharField"),
    m.Name("CommaSeparatedIntegerField"),
    m.Name("DateField"),
    m.Name("DateTimeField"),
    m.Name("DecimalField"),
    m.Name("DurationField"),
    m.Name("EmailField"),
    m.Name("FileField"),
    m.Name("FilePathField"),
    m.Name("FloatField"),
    m.Name("ForeignKey"),
    m.Name("GenericIPAddressField"),
    m.Name("IPAddressField"),
    m.Name("ImageField"),
    m.Name("IntegerField"),
    m.Name("JSONField"),
    m.Name("ManyToManyField"),
    m.Name("NullBooleanField"),
    m.Name("OneToOneField"),
    m.Name("PositiveBigIntegerField"),
    m.Name("PositiveIntegerField"),
    m.Name("PositiveSmallIntegerField"),
    m.Name("SlugField"),
    m.Name("SmallAutoField"),
    m.Name("SmallIntegerField"),
    m.Name("TextField"),
    m.Name("TimeField"),
    m.Name("URLField"),
    m.Name("UUIDField"),
)
